export {
  AdminSettingsProvider,
  useAdminSettings,
  useAdminSettingsSafe,
  useCanUploadAttachments,
  useCanUseMediaLibraryAttachments,
  useCanDownloadAttachments,
  useCanShowExternalImages,
  useMaxAttachmentSizeMb,
  useSyncIntervalMinutes,
  useAutoSyncDisabled,
  useWhitelabelDefaultLayout,
  useWhitelabelDefaultTheme,
  useAllowUserLayoutSwitching,
  useAllowUserThemeSwitching,
  useAllowUserModeSwitching,
} from "./AdminSettingsContext";
