/**
 * Standard sidebar folder order: single source of truth.
 *
 * Every layout variant lists canonical system folders in this fixed sequence
 * before any custom folders. Virtual views such as Important, Starred, and
 * Scheduled are generated by the UI separately from provider folder rows.
 */

import type { SystemFolderType } from "@/services/interfaces";

/** Fixed order shown in every layout's sidebar before custom folders. */
export const STANDARD_FOLDER_ORDER: SystemFolderType[] = [
  "inbox",
  "sent",
  "drafts",
  "archive",
  "spam",
  "trash",
  "snoozed",
];

/** Virtual views rendered separately from real/provider mailbox folders. */
export const VIRTUAL_VIEW_ORDER: SystemFolderType[] = [
  "important",
  "starred",
  "scheduled",
];

const ORDER_INDEX = new Map<SystemFolderType, number>(
  STANDARD_FOLDER_ORDER.map((type, index) => [type, index]),
);

function normalizeStandardType(
  type: SystemFolderType | undefined,
): SystemFolderType | undefined {
  if (type === "junk") return "spam";
  return type;
}

/** Position in the standard block, or Infinity for non-standard/unknown types. */
export function standardOrderIndex(type: SystemFolderType | undefined): number {
  const normalizedType = normalizeStandardType(type);
  return normalizedType !== undefined && ORDER_INDEX.has(normalizedType)
    ? ORDER_INDEX.get(normalizedType)!
    : Infinity;
}

/** Whether a system folder type belongs to the fixed standard block. */
export function isStandardFolderType(
  type: SystemFolderType | undefined,
): boolean {
  const normalizedType = normalizeStandardType(type);
  return normalizedType !== undefined && ORDER_INDEX.has(normalizedType);
}

/**
 * Split folders into the ordered standard block + the custom remainder.
 * `standard` is sorted into {@link STANDARD_FOLDER_ORDER} regardless of input
 * order; `custom` keeps the input order for everything else.
 */
export function partitionFolders<T extends { systemType?: SystemFolderType }>(
  folders: readonly T[],
): { standard: T[]; custom: T[] } {
  const standard = folders
    .filter((folder) => isStandardFolderType(folder.systemType))
    .slice()
    .sort(
      (a, b) =>
        standardOrderIndex(a.systemType) - standardOrderIndex(b.systemType),
    );
  const custom = folders.filter(
    (folder) => !isStandardFolderType(folder.systemType),
  );
  return { standard, custom };
}
